### ISSUE TITLE
Begin end

### ISSUE THREAD

**Issue by fkolenak** [Yggdrasil88/FJPCompiller#2]
@jstrolen 
Cau, prave testuju v case kdyz chces pouzit blok s begin end tak to stejme vezme jen ten prvni prikaz: testovano na kodu:

```
const a = -1;
var v;
begin 
    v = = 1111;
    switch a 
    case 0:
        v = = -444;,
    case -1:
    begin 
        v = = 111;
        v = = 333;
    end
end
return;
```

zkus si ubrat pripadne pridat radky v tom bloku, kod se ani nehne :]

EDIT: tak jsem to vyzkousel na do while, blok to taky ignoruje a bere jen prvni prikaz

```
var v;
begin
    v = = 2;
    do
    begin
        v = = v - 1;
        v = = v - 2222;
    end
    while v >= 0;
end
return;
```

EDIT: Vseobecne <b>begin end</b> neni uplne v poradku.

**Comment by jstrolen** [comment]
@Yggdrasil88  
Diky, ze ses do toho dal. 

Mas pravdu, u if, else, do-while, while-do i switche byla chyba v generovanem strome a v naslednem prochazeni prislusnych vetvy. Uz by to melo byt opraveno. Zkus to tedy prosimte ve vsech pripadech znovu.

**Comment by fkolenak** [comment]
@jstrolen 
Ahoy,
tak znovu zkousim funkcnost tech begin end.

```
var v;
begin
    if v == -44 then
        begin
            v = = 222;

        end 
    else 
        begin
            v = = 666;
            v = = 999;
        end 
end
return;
```

Tak ted to smaze kompletne else vetev, nebo ona tam je, ale bez jedineho prikazu. U ostatnich prikazu to dela to same.
Jinak bez toho prikazy funguji podle ocekavani.

**Comment by jstrolen** [comment]
@Yggdrasil88  
Tak ted nevim, mas urcite tu posledni verzi programu? Me se zda, ze mi to na prikladu vyse funguje. Kdyz to tam zadam dostanu tohle: 

```
0 INT 0 5  //3x Hlavicka, 1x pomocna promenna, 1x promenna v
1 LOD 0 4  //Jsme v ifu, nacitame v
2 LIT 0 -44  //Pridame konstantu -44
3 OPR 0 8  //Porovnani na rovnost
4 JMC 0 8  //Pokud se nerovnaji, skok na else vetev
5 LIT 0 222  //TRUE vetev - Pridani konstanty 222 na vrchol zasobniku
6 STO 0 4  //Ulozeni do v
7 JMP 0 12  //Skok na konec if-else prikazu
8 LIT 0 666  //ELSE vetev - Pridani konstanty 666 na vrchol zasobniku
9 STO 0 4  //Ulozeni do v
10 LIT 0 999  //Pridani konstanty 999 na vrchol zasobniku
11 STO 0 4  //Ulozeni do v
12 RET 0 0  //Konec
```

Generuji ti to taky tenhle kod?

U tohohle kodu mi napada, ze mame nedefinovane chovani, pokud je vytvorena nova promenna, ale neni inicializovana - jako ted "v". Muzeme to vyresit tak, ze ji inicializujeme na nulu, nebo to nechame byt a nebudeme resit - nedefinovane chovani, asi jako v Ccku (v prvnim pripade by to byla prace na 5 minut, kdy zmenime INT na LITy). Vyberte si.

**Comment by fkolenak** [comment]
@jstrolen 
Mel jsem stayenou novou veryi, ale asi se mi stejne pustila ta stara. Jo mas pravdu jde to. Zitra odskousim jestli to jde teda vsude :]
